apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.firebase_service_account_secret_name }}
data:
  {{ .Values.firebase_service_account_file_name }}: {{ .Values.firebase_service_account_file_base64 }}