apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coc-main
spec:
  tls:
    - secretName: coc-certificate
      hosts:
      - {{ .Values.host }}
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /s1
            pathType: ImplementationSpecific
            backend:
              service:
                name: coc-service
                port:
                  number: 81
          - path: /backup/watchlist
            pathType: ImplementationSpecific
            backend:
              service:
                name: coc-service
                port:
                  number: 80