apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coc-main
spec:
  tls:
    - secretName: coc-certificate
      hosts:
      - {{ .Values.host }}
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /s1
            pathType: ImplementationSpecific
            backend:
              service:
                name: service1
                port:
                  number: 443
          - path: /s2
            pathType: ImplementationSpecific
            backend:
              service:
                name: service2
                port:
                  number: 80
          - path: /s3
            pathType: ImplementationSpecific
            backend:
              service:
                name: service1
                port:
                  number: 8089